name: docker build and push

on:
  push:
    tags:
      - v*

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: puppeteer
  SCOPE: puppeteer-renderer

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          t: ${{ env.REGISTRY }}/lightcode/${{env.IMAGE_NAME}}:latest
          build-args: |
            SCOPE=${{ env.SCOPE }}
            PORT=3000
          tags: ${{ steps.meta.outputs.tags }}

